# Site settings
author: Michelle Lu
title: 
header-img: img/home-bg.png
email: lu.michelle96@icloud.com
copyright_name: Michelle Lu
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lumichelle96

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
